Repository 9oormthon-univ/2025_SEASONTHON_TEAM_81_BE, pull requests merged in 2025-09, with the labels that each got.

#4 [Feat] 도메인 모델 및 API 기본 구조 설정
  src/main/java/com/goormthon/backend/mindwalk/domain/auth/api/AuthController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/auth/api/docs/AuthControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/auth/application/AuthService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/checkpoint/api/CheckpointController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/checkpoint/api/docs/CheckpointControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/checkpoint/application/CheckpointService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/checkpoint/dao/CheckpointRepository.java
  src/main/java/com/goormthon/backend/mindwalk/domain/checkpoint/domain/Checkpoint.java
  src/main/java/com/goormthon/backend/mindwalk/domain/checkpoint/domain/HealingContentType.java
  src/main/java/com/goormthon/backend/mindwalk/domain/checkpoint/domain/VisitStatus.java
  src/main/java/com/goormthon/backend/mindwalk/domain/common/BaseTimeEntity.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/api/GardenController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/api/docs/GardenControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/application/GardenService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/dao/GardenRepository.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/domain/FlowerType.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/domain/Garden.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/domain/GardenPlant.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/domain/PlantStage.java
  src/main/java/com/goormthon/backend/mindwalk/domain/notification/api/NotificationController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/notification/api/docs/NotificationApi.java
  src/main/java/com/goormthon/backend/mindwalk/domain/notification/application/NotificationService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/report/api/ReportController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/report/api/docs/ReportControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/report/application/ReportService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/api/UserController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/api/docs/UserControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/application/UserService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/dao/UserRepository.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/domain/User.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/api/WalkMissionController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/api/docs/WalkMissionControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/application/WalkMissionService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/dao/WalkMissionRepository.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/domain/WalkMission.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/domain/WalkMissionStatus.java
  src/main/java/com/goormthon/backend/mindwalk/global/config/swagger/SwaggerConfig.java
  src/main/java/com/goormthon/backend/mindwalk/global/config/web/WebConfig.java
  src/main/resources/application-docs.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#6 [chore] CodeRabbit 설정 파일 추가
  .coderabbit.yaml
Labels: ⚙ Setting

#8 [Deploy] GitHub Actions를 이용한 CI/CD 배포 자동화 구축
  .env.example
  .github/workflows/deploy.yml
  .gitignore
  src/main/resources/application-prod.yml
Labels: 🌏 Deploy

#12 [Feat/#11] 회원 정보 관리
  src/main/java/com/goormthon/backend/mindwalk/domain/auth/application/JwtProvider.java
  src/main/java/com/goormthon/backend/mindwalk/domain/auth/presentation/AuthenticatedIdResolver.java
  src/main/java/com/goormthon/backend/mindwalk/domain/auth/presentation/annotation/AuthenticatedId.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/api/UserController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/api/docs/UserControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/application/UserService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/dto/request/UserNicknameRequest.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/dto/request/UserNotificationRequest.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/goormthon/backend/mindwalk/global/config/web/WebConfig.java
Labels: ✨ Feature

#28 [Feat] 정원 정보 조회 API 구현 및 산책 완료 로직 리팩토링
  .coderabbit.yaml
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/application/GardenService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/dao/GardenPlantRepository.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/domain/GardenPlant.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/dto/response/GetGardenInfoResponse.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/dto/response/GetGrowingPlantInfoResponse.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/application/WalkMissionService.java
Labels: ✨ Feature, 🔨 Refactor

#32 [Feat] 마이페이지 조회 API에 산책 횟수 및 피운 꽃 개수 필드 추가
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/dao/GardenPlantRepository.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/application/UserService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/dao/WalkMissionRepository.java
Labels: ✨ Feature

#34 [Feat] 사용자가 수집한 꽃이 언제 피었는지 시간 정보 추가
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/domain/GardenPlant.java
  src/main/java/com/goormthon/backend/mindwalk/domain/garden/dto/response/GetGardenInfoResponse.java
Labels: ✨ Feature

#36 [Feat] 산책 미션 완료 기능 추가
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/api/WalkMissionController.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/api/docs/WalkMissionControllerDocs.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/application/WalkMissionService.java
  src/main/java/com/goormthon/backend/mindwalk/domain/walkmission/dao/WalkMissionRepository.java
Labels: ✨ Feature
